// 餐點資料庫
// spicy: 0 = 不辣, 1 = 小辣, 2 = 很辣
// mealType: "正餐" | "湯品" | "點心甜點" | "飲料"
// budget: 1 = 平價, 2 = 中等, 3 = 奢侈
// moods: 適合的心情標籤（開心 / 普通 / 有點累 / 療癒 / 放縱）
// ending: 對應的「終焉」結局類型，見 ENDINGS
const FOODS = [
  { name: "牛肉麵", category: "中式", spicy: 1, mealType: "正餐", budget: 2, moods: ["療癒", "普通"], emoji: "🍜", ending: "warm" },
  { name: "滷肉飯", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["療癒", "有點累", "普通"], emoji: "🍚", ending: "nostalgic" },
  { name: "水餃", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["有點累", "普通"], emoji: "🥟", ending: "warm" },
  { name: "麻辣火鍋", category: "中式", spicy: 2, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🍲", ending: "fiery" },
  { name: "小籠包", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🥟", ending: "grand" },
  { name: "宮保雞丁", category: "中式", spicy: 1, mealType: "正餐", budget: 2, moods: ["普通", "開心"], emoji: "🍗", ending: "adventure" },
  { name: "廣東粥", category: "中式", spicy: 0, mealType: "湯品", budget: 1, moods: ["療癒", "有點累"], emoji: "🥣", ending: "calm" },
  { name: "臭豆腐", category: "中式", spicy: 1, mealType: "點心甜點", budget: 1, moods: ["放縱", "普通"], emoji: "🧊", ending: "adventure" },

  { name: "義大利麵", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["普通", "開心"], emoji: "🍝", ending: "romantic" },
  { name: "漢堡", category: "西式", spicy: 0, mealType: "正餐", budget: 1, moods: ["放縱", "有點累"], emoji: "🍔", ending: "festive" },
  { name: "牛排", category: "西式", spicy: 0, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🥩", ending: "grand" },
  { name: "披薩", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["放縱", "開心"], emoji: "🍕", ending: "festive" },
  { name: "沙拉", category: "西式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "療癒"], emoji: "🥗", ending: "fresh" },
  { name: "三明治", category: "西式", spicy: 0, mealType: "正餐", budget: 1, moods: ["有點累", "普通"], emoji: "🥪", ending: "calm" },
  { name: "濃湯", category: "西式", spicy: 0, mealType: "湯品", budget: 1, moods: ["療癒", "有點累"], emoji: "🍲", ending: "warm" },

  { name: "壽司", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍣", ending: "romantic" },
  { name: "拉麵", category: "日式", spicy: 1, mealType: "湯品", budget: 2, moods: ["療癒", "有點累"], emoji: "🍜", ending: "nostalgic" },
  { name: "咖哩飯", category: "日式", spicy: 1, mealType: "正餐", budget: 1, moods: ["療癒", "普通"], emoji: "🍛", ending: "adventure" },
  { name: "天婦羅", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["普通", "開心"], emoji: "🍤", ending: "fresh" },
  { name: "丼飯", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["有點累", "普通"], emoji: "🍱", ending: "calm" },
  { name: "章魚燒", category: "日式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🐙", ending: "festive" },

  { name: "部隊鍋", category: "韓式", spicy: 2, mealType: "湯品", budget: 2, moods: ["放縱", "療癒"], emoji: "🍲", ending: "fiery" },
  { name: "韓式炸雞", category: "韓式", spicy: 1, mealType: "正餐", budget: 2, moods: ["放縱", "開心"], emoji: "🍗", ending: "festive" },
  { name: "石鍋拌飯", category: "韓式", spicy: 1, mealType: "正餐", budget: 2, moods: ["普通", "療癒"], emoji: "🍚", ending: "warm" },
  { name: "辣炒年糕", category: "韓式", spicy: 2, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🌶️", ending: "fiery" },

  { name: "越南河粉", category: "東南亞", spicy: 0, mealType: "湯品", budget: 1, moods: ["療癒", "有點累"], emoji: "🍜", ending: "fresh" },
  { name: "打拋豬", category: "東南亞", spicy: 2, mealType: "正餐", budget: 1, moods: ["普通", "開心"], emoji: "🌶️", ending: "fiery" },
  { name: "月亮蝦餅", category: "東南亞", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["放縱", "開心"], emoji: "🍤", ending: "mystic" },

  { name: "珍珠奶茶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "放縱"], emoji: "🧋", ending: "mystic" },
  { name: "咖啡", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "有點累"], emoji: "☕", ending: "calm" },
  { name: "鬆餅", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🧇", ending: "romantic" },
  { name: "蛋糕", category: "不限", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱", "療癒"], emoji: "🍰", ending: "romantic" },
  { name: "剉冰", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍧", ending: "fresh" },

  { name: "蚵仔煎", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🦪", ending: "grand" },
  { name: "麻婆豆腐", category: "中式", spicy: 2, mealType: "正餐", budget: 1, moods: ["放縱", "開心"], emoji: "🌶️", ending: "fiery" },
  { name: "京醬肉絲", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["普通", "療癒"], emoji: "🥢", ending: "warm" },
  { name: "蔥油餅", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["有點累", "普通"], emoji: "🫓", ending: "nostalgic" },
  { name: "水煮魚", category: "中式", spicy: 2, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🐟", ending: "fiery" },
  { name: "燒賣", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🥟", ending: "grand" },
  { name: "東坡肉", category: "中式", spicy: 0, mealType: "正餐", budget: 3, moods: ["放縱", "療癒"], emoji: "🍖", ending: "grand" },
  { name: "擔仔麵", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["療癒", "有點累"], emoji: "🍜", ending: "nostalgic" },

  { name: "焗烤通心粉", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["療癒", "普通"], emoji: "🧀", ending: "warm" },
  { name: "墨西哥捲餅", category: "西式", spicy: 1, mealType: "正餐", budget: 1, moods: ["開心", "普通"], emoji: "🌯", ending: "adventure" },
  { name: "炸魚薯條", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["普通", "有點累"], emoji: "🍟", ending: "nostalgic" },
  { name: "燉飯", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "療癒"], emoji: "🍚", ending: "romantic" },
  { name: "法式吐司", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍞", ending: "romantic" },
  { name: "貝果", category: "西式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "有點累"], emoji: "🥯", ending: "calm" },
  { name: "起司鍋", category: "西式", spicy: 0, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🧀", ending: "grand" },

  { name: "親子丼", category: "日式", spicy: 0, mealType: "正餐", budget: 1, moods: ["療癒", "有點累"], emoji: "🍚", ending: "warm" },
  { name: "味噌湯", category: "日式", spicy: 0, mealType: "湯品", budget: 1, moods: ["療癒", "普通"], emoji: "🍲", ending: "calm" },
  { name: "烏龍麵", category: "日式", spicy: 0, mealType: "湯品", budget: 1, moods: ["有點累", "普通"], emoji: "🍜", ending: "calm" },
  { name: "燒肉", category: "日式", spicy: 0, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🥩", ending: "festive" },
  { name: "大阪燒", category: "日式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🥞", ending: "festive" },
  { name: "可樂餅", category: "日式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "有點累"], emoji: "🥔", ending: "nostalgic" },
  { name: "炸豬排", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍱", ending: "warm" },

  { name: "韓式冷麵", category: "韓式", spicy: 1, mealType: "正餐", budget: 2, moods: ["普通", "開心"], emoji: "🍜", ending: "fresh" },
  { name: "韓式泡菜鍋", category: "韓式", spicy: 2, mealType: "湯品", budget: 2, moods: ["療癒", "放縱"], emoji: "🍲", ending: "fiery" },
  { name: "辣拌麵", category: "韓式", spicy: 2, mealType: "正餐", budget: 1, moods: ["開心", "放縱"], emoji: "🌶️", ending: "fiery" },
  { name: "紫菜飯捲", category: "韓式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "有點累"], emoji: "🍙", ending: "fresh" },
  { name: "起司炸雞", category: "韓式", spicy: 0, mealType: "正餐", budget: 2, moods: ["放縱", "開心"], emoji: "🍗", ending: "festive" },

  { name: "泰式綠咖哩", category: "東南亞", spicy: 2, mealType: "正餐", budget: 2, moods: ["開心", "放縱"], emoji: "🍛", ending: "fiery" },
  { name: "叻沙", category: "東南亞", spicy: 1, mealType: "湯品", budget: 2, moods: ["療癒", "普通"], emoji: "🍜", ending: "adventure" },
  { name: "星洲炒米", category: "東南亞", spicy: 1, mealType: "正餐", budget: 1, moods: ["普通", "開心"], emoji: "🍝", ending: "adventure" },
  { name: "越式春捲", category: "東南亞", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "療癒"], emoji: "🥢", ending: "fresh" },
  { name: "泰式酸辣蝦湯", category: "東南亞", spicy: 2, mealType: "湯品", budget: 2, moods: ["放縱", "療癒"], emoji: "🍤", ending: "fiery" },

  { name: "熱可可", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["療癒", "有點累"], emoji: "🍫", ending: "warm" },
  { name: "氣泡飲", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "放縱"], emoji: "🥤", ending: "fresh" },
  { name: "布丁", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍮", ending: "nostalgic" },
  { name: "提拉米蘇", category: "不限", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱"], emoji: "🍰", ending: "romantic" },
  { name: "馬卡龍", category: "不限", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "療癒"], emoji: "🍬", ending: "grand" },
  { name: "雞蛋仔", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🧇", ending: "festive" },

  { name: "餛飩麵", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["療癒", "有點累"], emoji: "🥟", ending: "warm" },
  { name: "蛋炒飯", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "有點累"], emoji: "🍳", ending: "nostalgic" },
  { name: "炒河粉", category: "中式", spicy: 1, mealType: "正餐", budget: 1, moods: ["開心", "普通"], emoji: "🍜", ending: "adventure" },
  { name: "蒸餃", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "開心"], emoji: "🥟", ending: "warm" },
  { name: "生煎包", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🥟", ending: "nostalgic" },
  { name: "韭菜盒子", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "有點累"], emoji: "🫓", ending: "nostalgic" },
  { name: "潤餅", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "開心"], emoji: "🌯", ending: "fresh" },
  { name: "肉圓", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "療癒"], emoji: "🍡", ending: "nostalgic" },
  { name: "大腸麵線", category: "中式", spicy: 1, mealType: "正餐", budget: 1, moods: ["療癒", "有點累"], emoji: "🍜", ending: "nostalgic" },
  { name: "鹹酥雞", category: "中式", spicy: 1, mealType: "點心甜點", budget: 1, moods: ["放縱", "開心"], emoji: "🍗", ending: "festive" },
  { name: "蘿蔔糕", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "有點累"], emoji: "🍘", ending: "warm" },
  { name: "臘肉飯", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["療癒", "普通"], emoji: "🍚", ending: "warm" },
  { name: "叉燒飯", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍚", ending: "grand" },
  { name: "燒臘飯", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍗", ending: "grand" },
  { name: "白斬雞", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["普通", "療癒"], emoji: "🍗", ending: "calm" },
  { name: "鹹水雞", category: "中式", spicy: 1, mealType: "點心甜點", budget: 1, moods: ["放縱", "開心"], emoji: "🍗", ending: "fresh" },
  { name: "酸菜白肉鍋", category: "中式", spicy: 0, mealType: "湯品", budget: 2, moods: ["療癒", "放縱"], emoji: "🍲", ending: "warm" },
  { name: "酸辣湯", category: "中式", spicy: 1, mealType: "湯品", budget: 1, moods: ["有點累", "療癒"], emoji: "🍲", ending: "warm" },
  { name: "紫菜蛋花湯", category: "中式", spicy: 0, mealType: "湯品", budget: 1, moods: ["療癒", "普通"], emoji: "🍲", ending: "calm" },
  { name: "揚州炒飯", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "開心"], emoji: "🍚", ending: "nostalgic" },
  { name: "蝦仁炒飯", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍚", ending: "grand" },
  { name: "客家小炒", category: "中式", spicy: 1, mealType: "正餐", budget: 2, moods: ["開心", "放縱"], emoji: "🥢", ending: "adventure" },
  { name: "薑母鴨", category: "中式", spicy: 1, mealType: "湯品", budget: 3, moods: ["療癒", "放縱"], emoji: "🦆", ending: "warm" },
  { name: "羊肉爐", category: "中式", spicy: 1, mealType: "湯品", budget: 3, moods: ["療癒", "放縱"], emoji: "🍲", ending: "warm" },
  { name: "佛跳牆", category: "中式", spicy: 0, mealType: "湯品", budget: 3, moods: ["放縱", "開心"], emoji: "🍲", ending: "grand" },
  { name: "紅燒獅子頭", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["療癒", "普通"], emoji: "🍖", ending: "warm" },
  { name: "糖醋排骨", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍖", ending: "grand" },
  { name: "回鍋肉", category: "中式", spicy: 2, mealType: "正餐", budget: 2, moods: ["放縱", "開心"], emoji: "🌶️", ending: "fiery" },
  { name: "魚香肉絲", category: "中式", spicy: 1, mealType: "正餐", budget: 2, moods: ["普通", "開心"], emoji: "🥢", ending: "adventure" },
  { name: "乾煸四季豆", category: "中式", spicy: 1, mealType: "正餐", budget: 1, moods: ["普通", "療癒"], emoji: "🥦", ending: "adventure" },
  { name: "蒜泥白肉", category: "中式", spicy: 1, mealType: "正餐", budget: 2, moods: ["開心", "放縱"], emoji: "🥩", ending: "adventure" },
  { name: "口水雞", category: "中式", spicy: 2, mealType: "點心甜點", budget: 2, moods: ["放縱", "開心"], emoji: "🌶️", ending: "fiery" },
  { name: "擔擔麵", category: "中式", spicy: 2, mealType: "正餐", budget: 1, moods: ["開心", "放縱"], emoji: "🌶️", ending: "fiery" },
  { name: "炸醬麵", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "有點累"], emoji: "🍜", ending: "nostalgic" },
  { name: "陽春麵", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["療癒", "有點累"], emoji: "🍜", ending: "calm" },
  { name: "鍋貼", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "開心"], emoji: "🥟", ending: "nostalgic" },
  { name: "刈包", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["放縱", "開心"], emoji: "🥪", ending: "festive" },
  { name: "蔥抓餅", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "有點累"], emoji: "🫓", ending: "nostalgic" },
  { name: "蛋餅", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "有點累"], emoji: "🍳", ending: "calm" },
  { name: "燒餅油條", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["療癒", "有點累"], emoji: "🥖", ending: "nostalgic" },
  { name: "豆漿", category: "中式", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "療癒"], emoji: "🥛", ending: "calm" },
  { name: "米漿", category: "中式", spicy: 0, mealType: "飲料", budget: 1, moods: ["療癒", "普通"], emoji: "🥛", ending: "nostalgic" },
  { name: "花生湯", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "普通"], emoji: "🥣", ending: "warm" },
  { name: "芋圓", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "療癒"], emoji: "🍡", ending: "nostalgic" },
  { name: "豆花", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "開心"], emoji: "🍮", ending: "calm" },
  { name: "仙草凍", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "療癒"], emoji: "🍮", ending: "fresh" },
  { name: "燒仙草", category: "中式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "有點累"], emoji: "🍫", ending: "warm" },
  { name: "蒸蛋", category: "中式", spicy: 0, mealType: "湯品", budget: 1, moods: ["療癒", "普通"], emoji: "🍳", ending: "calm" },
  { name: "木須肉", category: "中式", spicy: 0, mealType: "正餐", budget: 2, moods: ["普通", "開心"], emoji: "🥢", ending: "adventure" },
  { name: "螞蟻上樹", category: "中式", spicy: 1, mealType: "正餐", budget: 1, moods: ["開心", "普通"], emoji: "🍜", ending: "adventure" },
  { name: "客家粄條", category: "中式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "療癒"], emoji: "🍜", ending: "nostalgic" },
  { name: "千層麵", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["療癒", "開心"], emoji: "🍝", ending: "romantic" },
  { name: "白醬義大利麵", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "療癒"], emoji: "🍝", ending: "romantic" },
  { name: "青醬義大利麵", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍝", ending: "fresh" },
  { name: "蒜香麵包", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "放縱"], emoji: "🥖", ending: "festive" },
  { name: "凱薩沙拉", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["普通", "療癒"], emoji: "🥗", ending: "fresh" },
  { name: "尼斯沙拉", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["普通", "療癒"], emoji: "🥗", ending: "fresh" },
  { name: "歐姆蛋", category: "西式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "有點累"], emoji: "🍳", ending: "calm" },
  { name: "班尼迪克蛋", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "放縱"], emoji: "🍳", ending: "romantic" },
  { name: "美式鬆餅", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🥞", ending: "festive" },
  { name: "比利時鬆餅", category: "西式", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱"], emoji: "🧇", ending: "romantic" },
  { name: "可頌", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🥐", ending: "romantic" },
  { name: "巧克力可頌", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🥐", ending: "romantic" },
  { name: "法式洋蔥湯", category: "西式", spicy: 0, mealType: "湯品", budget: 2, moods: ["療癒", "普通"], emoji: "🍲", ending: "warm" },
  { name: "蔬菜濃湯", category: "西式", spicy: 0, mealType: "湯品", budget: 1, moods: ["療癒", "有點累"], emoji: "🍲", ending: "calm" },
  { name: "烤雞腿排", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍗", ending: "grand" },
  { name: "烤羊排", category: "西式", spicy: 0, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🍖", ending: "grand" },
  { name: "烤鮭魚", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "療癒"], emoji: "🐟", ending: "fresh" },
  { name: "蟹肉濃湯", category: "西式", spicy: 0, mealType: "湯品", budget: 2, moods: ["療癒", "放縱"], emoji: "🍲", ending: "grand" },
  { name: "生蠔", category: "西式", spicy: 0, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🦪", ending: "grand" },
  { name: "淡菜", category: "西式", spicy: 1, mealType: "正餐", budget: 2, moods: ["開心", "放縱"], emoji: "🦪", ending: "adventure" },
  { name: "西班牙海鮮飯", category: "西式", spicy: 0, mealType: "正餐", budget: 3, moods: ["開心", "放縱"], emoji: "🥘", ending: "grand" },
  { name: "塔可", category: "西式", spicy: 1, mealType: "正餐", budget: 1, moods: ["開心", "普通"], emoji: "🌮", ending: "adventure" },
  { name: "法士達", category: "西式", spicy: 1, mealType: "正餐", budget: 2, moods: ["開心", "放縱"], emoji: "🌮", ending: "adventure" },
  { name: "起司漢堡", category: "西式", spicy: 0, mealType: "正餐", budget: 1, moods: ["放縱", "開心"], emoji: "🍔", ending: "festive" },
  { name: "培根蛋堡", category: "西式", spicy: 0, mealType: "正餐", budget: 1, moods: ["有點累", "普通"], emoji: "🥪", ending: "calm" },
  { name: "熱狗堡", category: "西式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "開心"], emoji: "🌭", ending: "festive" },
  { name: "炸雞柳", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["放縱", "開心"], emoji: "🍗", ending: "festive" },
  { name: "洋蔥圈", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["放縱", "普通"], emoji: "🧅", ending: "festive" },
  { name: "烤馬鈴薯", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "普通"], emoji: "🥔", ending: "calm" },
  { name: "法式薄餅", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🥞", ending: "romantic" },
  { name: "舒芙蕾", category: "西式", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱"], emoji: "🍮", ending: "romantic" },
  { name: "布朗尼", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["放縱", "開心"], emoji: "🍫", ending: "romantic" },
  { name: "起司蛋糕", category: "西式", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱"], emoji: "🍰", ending: "romantic" },
  { name: "紐約起司蛋糕", category: "西式", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱"], emoji: "🍰", ending: "grand" },
  { name: "蘋果派", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "開心"], emoji: "🥧", ending: "nostalgic" },
  { name: "檸檬塔", category: "西式", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "普通"], emoji: "🍋", ending: "fresh" },
  { name: "可麗露", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍮", ending: "romantic" },
  { name: "泡芙", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🍮", ending: "romantic" },
  { name: "馬林糖", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🤍", ending: "romantic" },
  { name: "卡布奇諾", category: "西式", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "療癒"], emoji: "☕", ending: "calm" },
  { name: "拿鐵咖啡", category: "西式", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "有點累"], emoji: "☕", ending: "calm" },
  { name: "摩卡咖啡", category: "西式", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "放縱"], emoji: "☕", ending: "romantic" },
  { name: "檸檬水", category: "西式", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "療癒"], emoji: "🍋", ending: "fresh" },
  { name: "冰淇淋", category: "西式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🍨", ending: "festive" },
  { name: "奶昔", category: "西式", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "放縱"], emoji: "🥤", ending: "festive" },
  { name: "藜麥沙拉", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["普通", "療癒"], emoji: "🥗", ending: "fresh" },
  { name: "帕尼尼", category: "西式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "有點累"], emoji: "🥪", ending: "calm" },
  { name: "酪梨吐司", category: "西式", spicy: 0, mealType: "正餐", budget: 2, moods: ["療癒", "普通"], emoji: "🥑", ending: "fresh" },
  { name: "蘑菇濃湯", category: "西式", spicy: 0, mealType: "湯品", budget: 1, moods: ["療癒", "有點累"], emoji: "🍲", ending: "calm" },
  { name: "生魚片", category: "日式", spicy: 0, mealType: "正餐", budget: 3, moods: ["開心", "放縱"], emoji: "🍣", ending: "fresh" },
  { name: "握壽司", category: "日式", spicy: 0, mealType: "正餐", budget: 3, moods: ["開心", "放縱"], emoji: "🍣", ending: "grand" },
  { name: "鰻魚飯", category: "日式", spicy: 0, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🍱", ending: "grand" },
  { name: "牛丼", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["有點累", "普通"], emoji: "🍚", ending: "calm" },
  { name: "豬肉丼", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["普通", "療癒"], emoji: "🍚", ending: "warm" },
  { name: "蕎麥麵", category: "日式", spicy: 0, mealType: "正餐", budget: 1, moods: ["療癒", "普通"], emoji: "🍜", ending: "fresh" },
  { name: "沾麵", category: "日式", spicy: 1, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍜", ending: "adventure" },
  { name: "味噌拉麵", category: "日式", spicy: 0, mealType: "湯品", budget: 2, moods: ["療癒", "有點累"], emoji: "🍜", ending: "warm" },
  { name: "豚骨拉麵", category: "日式", spicy: 0, mealType: "湯品", budget: 2, moods: ["療癒", "放縱"], emoji: "🍜", ending: "warm" },
  { name: "醬油拉麵", category: "日式", spicy: 0, mealType: "湯品", budget: 2, moods: ["療癒", "普通"], emoji: "🍜", ending: "nostalgic" },
  { name: "咖哩烏龍麵", category: "日式", spicy: 1, mealType: "湯品", budget: 2, moods: ["療癒", "普通"], emoji: "🍛", ending: "warm" },
  { name: "文字燒", category: "日式", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "普通"], emoji: "🥞", ending: "festive" },
  { name: "玉子燒", category: "日式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "療癒"], emoji: "🍳", ending: "calm" },
  { name: "唐揚炸雞", category: "日式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["放縱", "開心"], emoji: "🍗", ending: "festive" },
  { name: "炸蝦", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "放縱"], emoji: "🍤", ending: "fresh" },
  { name: "炸牡蠣", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["放縱", "開心"], emoji: "🦪", ending: "grand" },
  { name: "關東煮", category: "日式", spicy: 0, mealType: "湯品", budget: 1, moods: ["療癒", "有點累"], emoji: "🍢", ending: "warm" },
  { name: "飯糰", category: "日式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "有點累"], emoji: "🍙", ending: "calm" },
  { name: "茶泡飯", category: "日式", spicy: 0, mealType: "正餐", budget: 1, moods: ["有點累", "療癒"], emoji: "🍚", ending: "calm" },
  { name: "鯛魚燒", category: "日式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🐟", ending: "nostalgic" },
  { name: "大福", category: "日式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "療癒"], emoji: "🍡", ending: "romantic" },
  { name: "銅鑼燒", category: "日式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🥞", ending: "nostalgic" },
  { name: "抹茶蛋糕", category: "日式", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "療癒"], emoji: "🍵", ending: "romantic" },
  { name: "抹茶拿鐵", category: "日式", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "療癒"], emoji: "🍵", ending: "calm" },
  { name: "日式布丁", category: "日式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍮", ending: "nostalgic" },
  { name: "杏仁豆腐", category: "日式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "普通"], emoji: "🍮", ending: "fresh" },
  { name: "溫泉蛋", category: "日式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "普通"], emoji: "🥚", ending: "calm" },
  { name: "蒲燒鰻", category: "日式", spicy: 0, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🐟", ending: "grand" },
  { name: "壽喜燒", category: "日式", spicy: 0, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🍲", ending: "grand" },
  { name: "涮涮鍋", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["療癒", "放縱"], emoji: "🍲", ending: "warm" },
  { name: "茶碗蒸", category: "日式", spicy: 0, mealType: "湯品", budget: 1, moods: ["療癒", "普通"], emoji: "🍮", ending: "calm" },
  { name: "味噌鯖魚", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["療癒", "普通"], emoji: "🐟", ending: "warm" },
  { name: "照燒雞腿", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍗", ending: "grand" },
  { name: "日式炒麵", category: "日式", spicy: 0, mealType: "正餐", budget: 1, moods: ["開心", "普通"], emoji: "🍜", ending: "festive" },
  { name: "五目炊飯", category: "日式", spicy: 0, mealType: "正餐", budget: 2, moods: ["療癒", "普通"], emoji: "🍚", ending: "calm" },
  { name: "豬肉湯飯", category: "韓式", spicy: 1, mealType: "湯品", budget: 1, moods: ["療癒", "有點累"], emoji: "🍲", ending: "warm" },
  { name: "牛肉湯飯", category: "韓式", spicy: 1, mealType: "湯品", budget: 2, moods: ["療癒", "普通"], emoji: "🍲", ending: "warm" },
  { name: "韓式烤肉", category: "韓式", spicy: 0, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🥩", ending: "festive" },
  { name: "春川辣炒雞", category: "韓式", spicy: 2, mealType: "正餐", budget: 2, moods: ["開心", "放縱"], emoji: "🌶️", ending: "fiery" },
  { name: "辣炒豬肉", category: "韓式", spicy: 2, mealType: "正餐", budget: 2, moods: ["開心", "放縱"], emoji: "🌶️", ending: "fiery" },
  { name: "韓式炸醬麵", category: "韓式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "有點累"], emoji: "🍜", ending: "nostalgic" },
  { name: "海鮮蔥餅", category: "韓式", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "普通"], emoji: "🥞", ending: "festive" },
  { name: "泡菜煎餅", category: "韓式", spicy: 1, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🥞", ending: "fiery" },
  { name: "馬鈴薯排骨湯", category: "韓式", spicy: 1, mealType: "湯品", budget: 2, moods: ["療癒", "放縱"], emoji: "🍲", ending: "warm" },
  { name: "蔘雞湯", category: "韓式", spicy: 0, mealType: "湯品", budget: 2, moods: ["療癒", "普通"], emoji: "🍲", ending: "warm" },
  { name: "牛骨湯", category: "韓式", spicy: 0, mealType: "湯品", budget: 2, moods: ["療癒", "有點累"], emoji: "🍲", ending: "calm" },
  { name: "血腸", category: "韓式", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "開心"], emoji: "🌭", ending: "adventure" },
  { name: "辣魚湯", category: "韓式", spicy: 2, mealType: "湯品", budget: 2, moods: ["放縱", "療癒"], emoji: "🌶️", ending: "fiery" },
  { name: "醬油蟹", category: "韓式", spicy: 0, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🦀", ending: "grand" },
  { name: "辣醬蟹", category: "韓式", spicy: 2, mealType: "正餐", budget: 3, moods: ["放縱", "開心"], emoji: "🦀", ending: "fiery" },
  { name: "雜菜冬粉", category: "韓式", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "開心"], emoji: "🍜", ending: "fresh" },
  { name: "韓式豆腐鍋", category: "韓式", spicy: 2, mealType: "湯品", budget: 1, moods: ["療癒", "放縱"], emoji: "🍲", ending: "fiery" },
  { name: "韓式炒冬粉", category: "韓式", spicy: 0, mealType: "正餐", budget: 1, moods: ["開心", "普通"], emoji: "🍜", ending: "fresh" },
  { name: "蜂蜜奶油吐司", category: "韓式", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱"], emoji: "🍞", ending: "romantic" },
  { name: "韓式刨冰", category: "韓式", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱"], emoji: "🍧", ending: "festive" },
  { name: "泰式炒河粉", category: "東南亞", spicy: 1, mealType: "正餐", budget: 1, moods: ["開心", "普通"], emoji: "🍜", ending: "adventure" },
  { name: "打拋雞", category: "東南亞", spicy: 1, mealType: "正餐", budget: 1, moods: ["普通", "開心"], emoji: "🌶️", ending: "adventure" },
  { name: "紅咖哩", category: "東南亞", spicy: 2, mealType: "正餐", budget: 2, moods: ["開心", "放縱"], emoji: "🍛", ending: "fiery" },
  { name: "黃咖哩", category: "東南亞", spicy: 1, mealType: "正餐", budget: 2, moods: ["療癒", "普通"], emoji: "🍛", ending: "warm" },
  { name: "泰式椒麻雞", category: "東南亞", spicy: 1, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍗", ending: "adventure" },
  { name: "泰式涼拌木瓜絲", category: "東南亞", spicy: 1, mealType: "點心甜點", budget: 1, moods: ["普通", "療癒"], emoji: "🥗", ending: "fresh" },
  { name: "泰式涼拌海鮮", category: "東南亞", spicy: 2, mealType: "正餐", budget: 2, moods: ["開心", "放縱"], emoji: "🦐", ending: "fiery" },
  { name: "越式烤肉飯", category: "東南亞", spicy: 0, mealType: "正餐", budget: 2, moods: ["開心", "普通"], emoji: "🍚", ending: "adventure" },
  { name: "越式三明治", category: "東南亞", spicy: 0, mealType: "正餐", budget: 1, moods: ["普通", "有點累"], emoji: "🥖", ending: "fresh" },
  { name: "越式牛肉河粉", category: "東南亞", spicy: 0, mealType: "湯品", budget: 2, moods: ["療癒", "有點累"], emoji: "🍜", ending: "warm" },
  { name: "印尼炒飯", category: "東南亞", spicy: 1, mealType: "正餐", budget: 1, moods: ["普通", "開心"], emoji: "🍚", ending: "adventure" },
  { name: "沙嗲串", category: "東南亞", spicy: 1, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🍢", ending: "adventure" },
  { name: "馬來咖哩雞", category: "東南亞", spicy: 1, mealType: "正餐", budget: 2, moods: ["療癒", "普通"], emoji: "🍛", ending: "warm" },
  { name: "娘惹糕", category: "東南亞", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍡", ending: "mystic" },
  { name: "芒果糯米飯", category: "東南亞", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱"], emoji: "🥭", ending: "mystic" },
  { name: "泰式奶茶", category: "東南亞", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "普通"], emoji: "🧋", ending: "mystic" },
  { name: "越南咖啡", category: "東南亞", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "有點累"], emoji: "☕", ending: "calm" },
  { name: "檸檬香茅雞湯", category: "東南亞", spicy: 1, mealType: "湯品", budget: 2, moods: ["療癒", "普通"], emoji: "🍲", ending: "fresh" },
  { name: "蝦醬空心菜", category: "東南亞", spicy: 1, mealType: "正餐", budget: 1, moods: ["普通", "開心"], emoji: "🥬", ending: "adventure" },
  { name: "印尼炒麵", category: "東南亞", spicy: 1, mealType: "正餐", budget: 1, moods: ["開心", "普通"], emoji: "🍝", ending: "adventure" },
  { name: "綠茶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "療癒"], emoji: "🍵", ending: "calm" },
  { name: "紅茶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "有點累"], emoji: "🍵", ending: "calm" },
  { name: "烏龍茶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "療癒"], emoji: "🍵", ending: "calm" },
  { name: "檸檬茶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "普通"], emoji: "🍋", ending: "fresh" },
  { name: "水果茶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "療癒"], emoji: "🍹", ending: "fresh" },
  { name: "冬瓜茶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "療癒"], emoji: "🥤", ending: "nostalgic" },
  { name: "仙草茶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["療癒", "普通"], emoji: "🥤", ending: "calm" },
  { name: "麥茶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "有點累"], emoji: "🍵", ending: "calm" },
  { name: "可可拿鐵", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "放縱"], emoji: "🍫", ending: "romantic" },
  { name: "西瓜汁", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "普通"], emoji: "🍉", ending: "fresh" },
  { name: "芭樂汁", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "療癒"], emoji: "🍈", ending: "fresh" },
  { name: "蘋果汁", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "開心"], emoji: "🍎", ending: "fresh" },
  { name: "柳橙汁", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "普通"], emoji: "🍊", ending: "fresh" },
  { name: "蔬果昔", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["療癒", "普通"], emoji: "🥤", ending: "fresh" },
  { name: "優格", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "普通"], emoji: "🥛", ending: "fresh" },
  { name: "冰沙", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "放縱"], emoji: "🍧", ending: "festive" },
  { name: "芋頭牛奶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["療癒", "開心"], emoji: "🥤", ending: "nostalgic" },
  { name: "木瓜牛奶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "普通"], emoji: "🥤", ending: "fresh" },
  { name: "紅豆餅", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "普通"], emoji: "🥮", ending: "nostalgic" },
  { name: "車輪餅", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "開心"], emoji: "🥮", ending: "nostalgic" },
  { name: "雞蛋糕", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🧇", ending: "nostalgic" },
  { name: "地瓜球", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍡", ending: "festive" },
  { name: "龍鬚糖", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍬", ending: "nostalgic" },
  { name: "麥芽餅", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "療癒"], emoji: "🍪", ending: "nostalgic" },
  { name: "棉花糖", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🍬", ending: "festive" },
  { name: "蜜餞", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "療癒"], emoji: "🍬", ending: "nostalgic" },
  { name: "蛋捲", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "開心"], emoji: "🥠", ending: "nostalgic" },
  { name: "牛軋糖", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍬", ending: "nostalgic" },
  { name: "花生糖", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["普通", "療癒"], emoji: "🍬", ending: "nostalgic" },
  { name: "芝麻糊", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "有點累"], emoji: "🥣", ending: "warm" },
  { name: "綠豆湯", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "普通"], emoji: "🥣", ending: "calm" },
  { name: "紅豆湯", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "普通"], emoji: "🥣", ending: "warm" },
  { name: "銀耳蓮子湯", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "普通"], emoji: "🥣", ending: "calm" },
  { name: "杏仁茶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["療癒", "有點累"], emoji: "🥛", ending: "calm" },
  { name: "甜甜圈", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🍩", ending: "festive" },
  { name: "費南雪", category: "不限", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "普通"], emoji: "🍰", ending: "romantic" },
  { name: "瑪德蓮", category: "不限", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "普通"], emoji: "🍰", ending: "romantic" },
  { name: "司康", category: "不限", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["療癒", "普通"], emoji: "🥐", ending: "calm" },
  { name: "巧克力餅乾", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🍪", ending: "festive" },
  { name: "燕麥餅乾", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["療癒", "普通"], emoji: "🍪", ending: "calm" },
  { name: "爆米花", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍿", ending: "festive" },
  { name: "洋芋片", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["放縱", "開心"], emoji: "🥔", ending: "festive" },
  { name: "冰棒", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍦", ending: "nostalgic" },
  { name: "雪花冰", category: "不限", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱"], emoji: "🍧", ending: "festive" },
  { name: "芒果冰", category: "不限", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱"], emoji: "🍧", ending: "fresh" },
  { name: "抹茶冰淇淋", category: "不限", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "療癒"], emoji: "🍨", ending: "fresh" },
  { name: "香草冰淇淋", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "普通"], emoji: "🍨", ending: "romantic" },
  { name: "巧克力冰淇淋", category: "不限", spicy: 0, mealType: "點心甜點", budget: 1, moods: ["開心", "放縱"], emoji: "🍨", ending: "romantic" },
  { name: "黑糖鮮奶", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "療癒"], emoji: "🥛", ending: "nostalgic" },
  { name: "芋泥波霸", category: "不限", spicy: 0, mealType: "點心甜點", budget: 2, moods: ["開心", "放縱"], emoji: "🧋", ending: "mystic" },
  { name: "冬瓜檸檬", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "普通"], emoji: "🍋", ending: "fresh" },
  { name: "金桔檸檬", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["開心", "普通"], emoji: "🍋", ending: "fresh" },
  { name: "仙草凍飲", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["療癒", "普通"], emoji: "🥤", ending: "calm" },
  { name: "椰子水", category: "不限", spicy: 0, mealType: "飲料", budget: 1, moods: ["普通", "療癒"], emoji: "🥥", ending: "fresh" },
];

// 十種原創「終焉」結局：不重現任何動畫作品畫面，純粹以色調、光影、詩句營造史詩落幕感
const ENDINGS = {
  calm: {
    title: "靜謐終焉",
    line: "喧囂落幕，留下的只有恰到好處的安寧。",
    gradient: ["#1b2a4a", "#3a5a7a", "#a7c7e7"],
    particle: "stars",
  },
  warm: {
    title: "溫柔終焉",
    line: "像回家的那盞燈，永遠留一盞給你。",
    gradient: ["#3a2410", "#7a4a20", "#e8b06a"],
    particle: "embers",
  },
  nostalgic: {
    title: "懷舊終焉",
    line: "時間繞了一圈，你還是想念最初的味道。",
    gradient: ["#2a2015", "#5a4a30", "#c9a86a"],
    particle: "dust",
  },
  fiery: {
    title: "熱血終焉",
    line: "戰鬥結束的那一刻，痛快勝過一切。",
    gradient: ["#2a0e0e", "#7a1f1f", "#ff7043"],
    particle: "embers",
  },
  grand: {
    title: "華麗終焉",
    line: "這一餐，值得盛大登場。",
    gradient: ["#241033", "#5a2a7a", "#f2c94c"],
    particle: "confetti",
  },
  adventure: {
    title: "冒險終焉",
    line: "地圖的邊界，是下一口的起點。",
    gradient: ["#0e2a2a", "#1f5a5a", "#7ae0d8"],
    particle: "fireflies",
  },
  romantic: {
    title: "浪漫終焉",
    line: "有些美味，值得細細品味到最後一口。",
    gradient: ["#3a1030", "#7a2a5a", "#ffb3d1"],
    particle: "petals",
  },
  festive: {
    title: "狂歡終焉",
    line: "今天的主角，就是餐桌上的你。",
    gradient: ["#331a0e", "#8a3a1f", "#ffce54"],
    particle: "confetti",
  },
  fresh: {
    title: "清爽終焉",
    line: "洗去疲憊，從這一口重新開始。",
    gradient: ["#0e2a24", "#1f5a4a", "#8be0c9"],
    particle: "bubbles",
  },
  mystic: {
    title: "神秘終焉",
    line: "命運的籤，早已寫好答案。",
    gradient: ["#120a2e", "#2b1a52", "#8a6fd8"],
    particle: "stars",
  },
};

// 五個問題與選項定義
// miniGame: 當使用者選擇「不確定」時觸發的小遊戲類型（tarot / dice / lots / wheel）
// icon: 卡片上方顯示的大圖示；label: 卡片下方文字
const QUESTIONS = [
  {
    key: "mood",
    title: "今天心情如何？",
    miniGame: "tarot",
    options: [
      { value: "開心", icon: "😊", label: "開心" },
      { value: "普通", icon: "😐", label: "普通" },
      { value: "有點累", icon: "😪", label: "有點累" },
      { value: "療癒", icon: "🥺", label: "想療癒一下" },
      { value: "放縱", icon: "🎉", label: "想放縱一下" },
      { value: "__unsure__", icon: "🔮", label: "不確定，抽塔羅牌" },
    ],
  },
  {
    key: "spicy",
    title: "想吃辣的嗎？",
    miniGame: "dice",
    options: [
      { value: 0, icon: "🙅", label: "完全不辣" },
      { value: 1, icon: "🌶️", label: "小辣即可" },
      { value: 2, icon: "🔥", label: "越辣越好" },
      { value: "__unsure__", icon: "🎲", label: "不確定，擲骰子" },
    ],
  },
  {
    key: "category",
    title: "想吃哪種料理？",
    miniGame: "lots",
    options: [
      { value: "中式", icon: "🥟", label: "中式" },
      { value: "西式", icon: "🍝", label: "西式" },
      { value: "日式", icon: "🍣", label: "日式" },
      { value: "韓式", icon: "🍚", label: "韓式" },
      { value: "東南亞", icon: "🌶️", label: "東南亞" },
      { value: null, icon: "🌐", label: "不限" },
      { value: "__unsure__", icon: "🎋", label: "不確定，抽支籤" },
    ],
  },
  {
    key: "budget",
    title: "預算大概多少？",
    miniGame: "wheel",
    options: [
      { value: 1, icon: "💰", label: "平價" },
      { value: 2, icon: "💵", label: "中等" },
      { value: 3, icon: "💎", label: "奢侈" },
      { value: null, icon: "🌐", label: "不限" },
      { value: "__unsure__", icon: "🎡", label: "不確定，轉輪盤" },
    ],
  },
  {
    key: "mealType",
    title: "想吃正餐還是想吃點心？",
    miniGame: "wheel",
    options: [
      { value: "正餐", icon: "🍚", label: "正餐" },
      { value: "湯品", icon: "🍲", label: "湯品" },
      { value: "點心甜點", icon: "🍰", label: "點心甜點" },
      { value: "飲料", icon: "🧋", label: "飲料" },
      { value: null, icon: "🌐", label: "都可以" },
      { value: "__unsure__", icon: "🎡", label: "不確定，轉輪盤" },
    ],
  },
];
